#!/usr/bin/env bash
# extract_all_zip :現在ディレクトリ以下のzipファイルを全て展開する
# -----------------------------------------------------------------------------
readonly ME="$(basename ${0})"
readonly VERSION="1.0"

usage_exit() {
  [[ -n "${1}" ]] && echo "${1}" >&2
  echo "Usage: ${ME} dir"
  exit 1
}
version() {
  echo "${VERSION}"
}

IFS=$'\n'
# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
  local -r CURRENT_DIR="${1%/}"
  local zips
  local zip
  local dir

  [[ -z "${CURRENT_DIR}" ]] && usage_exit
  [[ ! -d "${CURRENT_DIR}" ]] && usage_exit "ディレクトリが存在しません"

  (
    cd "${CURRENT_DIR}"
    # zip展開するとまたzipが抽出される可能性があるため、なくなるまでループ
    while zips="$(ls | grep -E -x '^.*\.zip$')"; do

      for zip in ${zips}; do
        # 壊れているファイルの場合は名前を変更して除外する
        unzip -t "${zip}" > /dev/null 2>&1 || mv "${zip}" "${zip}.broken"
        # 展開し、元のファイルを削除
        # 同一ファイルが存在する場合は上書きする
        unzip -u "${zip}" && rm "${zip}"
      done
    done

    # ディレクトリを再帰
    for dir in $(find -mindepth 1 -maxdepth 1 -type d); do
      main "${dir}"
    done
  ) 
}

main "$@"
